name: BuildAndDeployApplication

trigger:
  - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-22.04'

variables:
  imageName: 'vilant/react-and-spring-rest'
  containerAppName: 'react-and-spring-rest'
  resourceGroup: 'rg-container-app'
  location: 'northeurope'

stages:
  - stage: tests
    displayName: Unit tests
    condition: eq(variables['Build.Reason'], 'PullRequest')  # Run only for pull requests
    jobs:
      - job: utests
        steps:
          - task: Maven@4
            inputs:
              goals: test

  - stage: build
    displayName: Build Image
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  # Run only for main branch
    jobs:
      - job: docker
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerRegistryServiceConnection'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
              addPipelineData: false

  - stage: provisioning
    displayName: Provisioning Azure Resources
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  # Run only for main branch
    jobs:
      - job: azureDeployment
        steps:
          - task: AzureCLI@2
            displayName: Create Azure resource group
            inputs:
              azureSubscription: 'azureResourceConnection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --name $(resourceGroup) --location $(location)

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Azure Bicep
            inputs:
              azureResourceManagerConnection: 'azureResourceConnection'
              deploymentScope: Resource Group
              resourceGroupName: $(resourceGroup)
              action: Create Or Update Resource Group
              location: $(location)
              csmFile: bicep/main.bicep
              overrideParameters: >
                      -image $(imageName)
                      -imageTag $(Build.BuildId)
                      -appName $(containerAppName)

  - stage: Destroy
    displayName: Destroy test environment
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  # Run only for main branch
    trigger: manual
    jobs:
      - job: azureDestroyResources
        steps:
          - task: AzureCLI@2
            displayName: Delete Azure resource group
            inputs:
              azureSubscription: 'azureResourceConnection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group delete --name $(resourceGroup) --yes
