name: BuildAndDeployApplication

trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'

variables:
  imageName: 'vilant/react-and-spring-rest'
  containerGroupName: 'react-and-spring-rest-group'
  containerName: 'react-and-spring-rest'
  resourceGroup: 'your-resource-group'
  location: 'your-location'

stages:
  - stage: build
    displayName: Build Image
    jobs:
      - job: docker
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerRegistryServiceConnection'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
              addPipelineData: false

  - stage: provisioning
    displayName: Provisioning Azure Resources
    jobs:
      - job: azureDeployment
        steps:
        - bash: |
            echo 'Deploy Bicep files'

  - stage: Destroy
    displayName: Destroy test environment
    trigger: manual
    jobs:
      - job: azureDestroyResources
        steps:
        - bash: |
            echo 'Hello World!'
